"""
Read Bridging Excel file to understand Multi-Property section
"""
import openpyxl
import warnings
warnings.filterwarnings('ignore')

# Read the Bridging Excel file
path = r'c:\Users\MFSD010.MFSUK-D010\Desktop\SF calc\polaristest\frontend\integration\samples\Issued - Bridge Calc 070126.xlsm'
wb = openpyxl.load_workbook(path, read_only=True, data_only=False)

print('=' * 70)
print('BRIDGING EXCEL - SHEET NAMES')
print('=' * 70)
for sheet in wb.sheetnames:
    print(f'  - {sheet}')

# Read KB_CRITERIA AND CALCULATION sheet
sheet = wb['KB_CRITERIA AND CALCULATION ']

print('=' * 70)
print('BTL EXCEL FORMULA VERIFICATION')
print('=' * 70)

print()
print('=' * 70)
print('1. NET LOAN FORMULA (Row 126)')
print('=' * 70)
print()
print('Formula: AL126 = IF(RoundDown,R126,Q126) - AD126 - AE126 - AH126')
print()
print('INTERPRETATION:')
print('  Net Loan = Gross Loan - Deferred Interest - Rolled Interest - Product Fee')
print()
print('Where:')
print('  AD126 = Deferred Interest = ((J126 * Gross) / 12) * Term')
print('  AE126 = Rolled Interest   = K126 * (PayRate/12) * Gross')
print('  AH126 = Product Fee')
print()
print('  J126 = Defer Int Percentage')
print('  K126 = Rolled months')
print()

print('=' * 70)
print('2. APRC FORMULA (BEFORE ROLLED - Rows 22-32, Column C/D)')
print('=' * 70)
print()
print('Cell D32 (APR/APRC): =D31/D29/D24*12')
print()
print('Where:')
print('  D31 = Total Int + Prod Fee = D30 + F27')
print('  D29 = Net Loan Amount = D23 - (D23*D26*D25) - (D23*D27)')
print('  D24 = Term (months)')
print()
print('Breaking down D31:')
print('  D30 = Total Int over term = D24 * F26')
print('  F27 = Product Fee Amount = D23 * D27 (Gross * Fee%)')
print()
print('Breaking down D30:')
print('  F26 = Monthly Interest Amount = D23 * D26 (Gross * Monthly Rate)')
print()
print('FINAL APRC FORMULA (Before Rolled):')
print('  APRC = (TotalInterest + ProductFee) / NetLoan / Term * 12')
print()
print('Which expands to:')
print('  APRC = ((Term * Gross * MonthlyRate) + (Gross * ProdFee%)) / NetLoan / Term * 12')
print()

print('=' * 70)
print('3. APRC FORMULA (AFTER ROLLED - Rows 22-32, Column I/L)')  
print('=' * 70)
print()
print('Cell L32: =L31/L29/L23*12')
print()
print('Where:')
print('  L31 = Total Int + Prod Fee = L30 + M27')
print('  L29 = Net Loan = L22 - M27 - M26 - M24 (Gross - ProdFee - ? - ?)')
print('  L23 = Duration (Months)')
print()
print('Breaking down L30:')
print('  L30 = Total Int = L23 * M25 + M26')
print('  L25 = Monthly Int Rate = (Tier_Standard_rate - DeferedIntP) / 12')
print('  L26 = Deferred Interest = DeferedIntPercent / 12')
print()

print('=' * 70)
print('4. COMPARISON WITH CODE')
print('=' * 70)
print()
print('CODE (btlCalculationEngine.js line 640-645):')
print('  const totalInterestCost = rolledInterestAmount + (directDebit * termMonths);')
print('  const aprc = ((totalRepayment - grossLoan) / grossLoan) * (12 / termMonths) * 100;')
print()
print('  Where: totalRepayment = grossLoan + totalInterestCost')
print('  So:    aprc = (totalInterestCost / grossLoan) * (12 / termMonths) * 100')
print()
print('EXCEL:')
print('  APRC = (TotalInterest + ProductFee) / NetLoan / Term * 12 * 100')
print()
print('KEY DIFFERENCES:')
print('  1. Excel divides by NET Loan, Code divides by GROSS Loan')
print('  2. Excel includes Product Fee in cost, Code uses totalInterestCost')
print('  3. The denominators are different (Net vs Gross)')
print()
